### ISSUE TITLE
Question about the branches

### ISSUE THREAD

**Issue by mscheltienne** [NataliiaMolch/spikes_detection_fcbg#1]
Hello @NataliiaMolch 

I am having a look at your project, which I forked to the FCBG repository.
I have a question about the branches, there is 'main' and 'version2'. Do you remember the difference between both, and which one should I focus on?

Thanks!

Mathieu

**Comment by NataliiaMolch** [comment]
Hello @mscheltienne,

Thank you for your questions. I have reviewed two branches and I think the "main" one is the final one. Potentially I could delete the version2...

Best,
Nataliia

**Comment by mscheltienne** [comment]
Ok thanks, that was my thought as well. I will delete the version2 on the FCBG fork.
